name: Delete Source Branch

on:
  pull_request:
    types: [ closed ]

jobs:
  delete_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Delete branch
        if: github.event.pull_request.merged == true
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}